language: java

notifications:
  email: false

services:
  - docker
  - mysql

before_install:
  - source tango.properties
  - wget https://github.com/tango-controls/TangoSourceDistribution/releases/download/${TANGO_SOURCE_DISTRIBUTION_VER}/tango-${TANGO_SOURCE_DISTRIBUTION_VER}.tar.gz
  - mkdir build
  - tar xf tango-${TANGO_SOURCE_DISTRIBUTION_VER}.tar.gz -C build

before_script:
  - docker build -t tango-build -f .travis/Dockerfile .
  - docker run --name tango-build -v `pwd`/build:/build -w=/build/tango-${TANGO_LIB_VER} -dit tango-build
  - docker exec tango-build ./configure --prefix=/build --disable-java --with-mysql-ho=127.0.0.1 --with-mysql-admin=root --with-mysql-admin-passwd=""
  - docker exec tango-build make && make install

script:
  - docker build .

after_script:
  - docker rm -f tango-build
  - docker rm -f mysql